services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_hiring_platform
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hiring_platform_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_CONTAINER_PORT} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  hiring_platform_network:
    # driver: bridge
    external: true

volumes:
  postgres_data: